CONNECT_INSTABOT_ACCOUNT = '*  Connect Instabot to your account \n'
DISCONNECT_INSTABOT_ACCOUNT = '* Disconnect Instabot from your account \n'
LAUNCH_FOLLOWER_MODULEDISCONNECT_INSTABOT_ACCOUNT = '*  Disconnect the instabot from your account \n'
LAUNCH_LIKE_MODULE =  '*  Launch the LIKE_MODULE \n'
LAUNCH_FOLLOWER_MODULE =  '*  Launch the FOLLOWER_MODULE \n'
LAUNCH_HYBRID_MODULE = '*  Launch the HYBRID_MODULE \n'
LAUNCH_UNFOLLOW_MODULE = '*  Launch the UNFOLLOW_MODULE \n'
LAUNCH_MUTE_MODULE =    '*  Launch the MUTE_MODULE \n'
OPEN_CONFIG_HELPER =  '*  Configure your Instabot \n'
RETURN_BACK = "Return back"

SEPARATOR_CONNECTION =  'CONNECTION'
SEPARATOR_DISCONNECT =  'DISCONNECT BOT'
SEPARATOR_MODULES = 'MODULES'
SEPARATOR_CONFIG_HELPER =  'CONFIGURATION HELPER'

